### PR TITLE
Implement equals and hashCode for expressions.

### PR DESCRIPTION
**Pull request by vlsi**
Proper equals/hashCode allows to detect duplicate expressions in BlockBuilder.
All the Expressions/Statements implement typical equals/hashCode provided by IntellijIDEA
ParameterExpression implement identity equals/hashCode

Hash codes for complex expressions are cached into a field of the expression.

### CODE REVIEW

**Comment by vlsi** [comment]
Oh, we need some better way to allow and prohibit reuse of expressions.
Initially I thought that right equals/hashCode would solve the problem, however one cannot just reuse expression, if it is of mutable type.

What do you think if linq4j would know which java types are immutable and which aren't?
Say, we allow to reuse primitive declarations, `String` declarations, `Enumerable` declarations and maybe some other classes.

This can **not** be reused

``` java
final SortedMultiMap multiMap0 = new SortedMultiMap();
```

However, this is fine to reuse

``` java
final Enumerable source0 = Linq4j.asEnumerable(new Integer[]{1});
```

This logic looks like flawed one:

``` java
        if (statement instanceof DeclarationStatement) {
          DeclarationStatement decl = (DeclarationStatement) statement;
          if ((decl.modifiers & Modifier.FINAL) != 0
              && decl.initializer != null
              && decl.initializer.equals(expression)) {
            return decl.parameter;
          }
        }
```

**Comment by julianhyde** [comment]
I don't think it's for linq4j to know whether expressions can be re-used. Only the code generating the expressions (e.g. optiq) can see the big picture.

Note that the `optimize` parameter of `BlockBuilder.append(String name, BlockStatement block, boolean optimize)` can control whether expressions are converted to variables. Use that mechanism, or maybe expand it.

The hashCode & equals stuff is helpful -- thanks.

I would like to make an Optiq release this week and that means a Linq4j release a day or two beforehand. Do you think you will need to make any Linq4j changes soon? If so I'll wait until you have them all in.

**Comment by vlsi** [comment]
Linq4j does have expression reuse test

I will update this PR shortly with `isImmutable` logic (just hardcode some well-known immutable classes). It passes all the tests, including optiq's ones.

I use linq4j only through optiq.

**Comment by vlsi** [comment]
Eventually better equality support for `DeclarationStatement` might be landed.
Currently, `ParameterExpression` is compared via identity, thus `DeclarationStatement` is effectively identity-compared, etc.

However, currently it is effectively forbidden to reuse expressions with declarations inside (i.e. the ones with state)

**Comment by vlsi** [comment]
Julian, please note that `a^b` kind of hash code (i.e. the former implementation for `BinaryExpression`) is weak. Xor is deemed to generate 0 hash codes when the operands are equal.

**Comment by vlsi** [comment]
Finally, I figured out that `optimize=true` parameter actually means "dear BlockBuilder, you can safely  reuse this expression declaration if you can".

Strangely, `BlockBuilder` does not consider if the expression to be reused was actually marked with "safe for reuse" mark or not. In other words, if we put "not-safe-for-reuse" expression, then exactly the same with "safe-for-reuse", then `BB` will reuse.

**Comment by julianhyde** [comment]
Rebased as https://github.com/julianhyde/linq4j/commit/e9ed8755244cf9de5377a7f5f98889f2d8412bd2 and https://github.com/julianhyde/linq4j/commit/a9f47857764254acc08d24786e0278c57b3bf9f1.

**Pull request closed without merging**
