### PR TITLE
Implemented firstOrDefault, single and singleOrDefault

### PR DESCRIPTION
**Pull request by danielcooperxyz**
first now throws NoSuchElementException and does not return null (this is the firstOrDefault functionality)
Fixed a number of checkstyle problems

### CODE REVIEW

**Comment by julianhyde** [comment]
Linq4j has been superseded by Apache Calcite. Can you please submit a pull request to https://github.com/apache/incubator-calcite? The files you patched are now in the org.apache.calcite.linq4j package of the linq4j module.

**Comment by JasonMing** [comment]
@julianhyde , I'm curious that will linq4j become standalone in recent ? I just check out the project "calcite", it is an awesome and huge project, but I just need the linq4j for iterating my collections conveniently.

**Comment by julianhyde** [comment]
@JasonMing, It made sense to make Linq4j part of Calcite because most of the developers were interested in using both together. But Calcite is divided into libraries, and you can use the calcite-linq4j library without using any of the other libraries. (Its only runtime dependency is guava.) In maven use groupId: "org.apache.calcite", artifactId: "calcite-linq4j", version: "1.3.0-incubating".

**Comment by julianhyde** [comment]
@JasonMing, PS Discussions about Linq4j on the Calcite dev list, and pull requests to https://github.com/apache/incubator-calcite will be most welcome.

**Comment by JasonMing** [comment]
@julianhyde Thanks for your answering, there is no doubt that Calcite is an excellent project, but my company policy is very strictly, they restrict the new technology getting in, especially the DB techs, so I can just use the standalone part linq4j. Because I comes from .Net platform and the Java's stream API is too sucks to use, especially the `.collect` method, there is no any hints to find the instance of `Collector` except you check out the document manually.

**Comment by julianhyde** [comment]
@JasonMing Sorry you're not able to use Calcite. Linq4j is still available open source so you can continue to use that. You could even fork on github and apply patches from Calcite.

**Pull request closed without merging**
