### PR TITLE
Enumerable first and contains

### PR DESCRIPTION
**Pull request by wseidel**
Hi,
Implements Enumerable.contains, EqualityComparer, first and first with predicate.

### CODE REVIEW

**Comment by julianhyde** [comment]
I will accept this pull request, but the history is complicated. Next time please `git pull rebase -i master` and squash to create a simple change history.

**Comment by wseidel** [comment]
Ok. Thanks for the tip. I will be careful. ;)

**Comment by julianhyde** [comment]
Oh, if I've merged a previous pull request to master, start your branch from that version of master if you can. I did some cleanups when I merged, and those cleanups created conflicts because your pull request was trying to re-apply older versions.

**Comment by julianhyde** [comment]
Merged as https://github.com/julianhyde/linq4j/commit/047d63eccf66d36578c79836a07a56cf14863105.

**Pull request closed without merging**
